# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messengersdeployment

spec:
  selector:
    matchLabels:
      app: messengers
  replicas: 1
  template:
    metadata:
      labels:
        app: messengers
    spec:
      containers:
      - name: mongodb
        image: mongo
        volumeMounts:
        - mountPath: ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
          name: mongo-init
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: messangers
      - name: api
        image: adidenkosd/messengers
        ports:
          - containerPort: 80
        env:
        - name: DbStoreSettings__ConnectionString
          value: mongodb://mongodb:27017
      volumes:
      - name: mongo-init